# Generated by Django 4.2 on 2025-10-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_factoryprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoryprofile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='factoryprofile',
            name='factory_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='factoryprofile',
            name='factory_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='factoryprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
