# Generated by Django 4.2 on 2025-10-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_remove_factoryprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factoryprofile',
            old_name='factory_name',
            new_name='name',
        ),
    ]
