# Generated by Django 4.2 on 2025-10-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
