# Generated by Django 4.2 on 2025-10-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='profile_picture',
            field=models.ImageField(blank=True, default='factory_logos/default.png', upload_to='factory_logos/'),
        ),
    ]
